-- Insert Day 1 - Day 7 for BookHub (Channel 1)
INSERT INTO digg_posts (channel_id, post_date, title, content, status) VALUES
(1, '2026-03-12', 'Amazon KDP''s silent print royalty cut for books under $9.99... How are you adapting your pricing strategy this year?', 'Since the royalty shift from 60% down to 50% for print books priced under $9.99 (for standard trim sizes), I''ve noticed a lot of panic in the low/no-content space. Are you raising your prices to $9.99 or absorbing the hit?', 'pending'),
(1, '2026-03-13', 'The move to DRM-free EPUB/PDF downloads on Kindle: Are you enabling it for your new releases?', 'In January, Amazon quietly started letting readers download DRM-free EPUBs and PDFs of Kindle books. This is a huge shift for accessibility. Have you seen any impact on sales or piracy concerns yet?', 'pending'),
(1, '2026-03-14', 'KDP now mandates alt text for all eBook images. Is this the end of lazy uploads?', 'Amazon is getting strict about accessibility. Every single image now needs alt text. It''s more work, but it might help with ranking if the AI can finally \"see\" our diagrams and maps.', 'pending'),
(1, '2026-03-15', 'Generative Engine Optimization (GEO) is the new SEO for authors. Is your book ChatGPT-ready?', 'People aren''t just searching Google for book recommendations anymore; they are asking Perplexity and ChatGPT. How do we make sure our author name pops up in their recommendations?', 'pending'),
(1, '2026-03-16', 'Direct-to-Reader sales via Shopify vs. KDP Exclusivity. Who is winning the 2026 platform war?', 'With indie authors earning 70-90% on Shopify compared to KDP''s cut, the math is starting to look very attractive. But can you survive without the Kindle Unlimited reach?', 'pending'),
(1, '2026-03-17', 'Is Amazon Ads getting more volatile or is it just me? Scaling in March 2026.', 'The bid wars for keywords are insane right now. I''ve seen my ACOS double this week. Anyone else noticing a shift in the AI-driven bidding system lately?', 'pending'),
(1, '2026-03-18', 'The Rise of Human Curators in an AI World. Why Bookstagram and Newsletters are still king.', 'Despite AI recommendations, readers still trust people. How are you building relationships with indie curators this year instead of just fighting the Amazon algorithm?', 'pending');

-- Insert Day 1 - Day 7 for BookClub (Channel 2)
INSERT INTO digg_posts (channel_id, post_date, title, content, status) VALUES
(2, '2026-03-12', 'Is the ''Typography-Only'' book cover trend finally dying in 2026?', 'For the last two years, minimalist covers with massive, stylized text dominated. But I''m seeing a shift back to conceptual illustration. What''s on your current TBR list? Bold text or beautiful art?', 'pending'),
(2, '2026-03-13', 'Keyword stuffing in titles/subtitles is dead. Performance-based ranking is taking over KDP.', 'Amazon''s A9 algorithm has been vicious lately toward books with \"stuffed\" subtitles. It seems they want clean, short titles and organic engagement now. A win for quality?', 'pending'),
(2, '2026-03-14', 'Bold Shapes and Grids: The 2026 Aesthetic for Mystery/Thriller covers.', 'I''ve noticed a ton of high-contrast, geometric designs on the bestseller lists this month. It organize the layout and guides the eye. Do you prefer this to the old moody photography?', 'pending'),
(2, '2026-03-15', 'Handcrafted and Painterly styles: A reaction to the AI-generated flood?', 'Visible brushstrokes and textured digital paintings are making a huge comeback. It feels more human. Are you seeing this in your favorite genres?', 'pending'),
(2, '2026-03-16', 'Dual Visibility: Designing covers for both Thumbnail and Print sizes.', 'A cover needs to pop as a 100px thumbnail on a phone screen AND look professional in print. Bold structure vs subtle detail—what''s your favorite cover this month?', 'pending'),
(2, '2026-03-17', 'High-Contrast Neon and Explosive Colors are taking over Contemporary Fiction.', 'Muted palettes are out. Saturated, high-contrast neons are everywhere in 2026. Does it make you more likely to click, or is it too much?', 'pending'),
(2, '2026-03-18', 'Is graphic minimalism in adult fiction getting too repetitive?', 'Every second book in the bookstore looks like a vector illustration right now. Are we reaching peak minimalism, or is there still room for this style to evolve?', 'pending');
